In [2]:
import pandas as pd

공원 데이터 처리

In [7]:
df_park = pd.read_csv(r"D:\MINNIE\contest_gyeongnam_data_analysis\data\경상남도_공원 현황_20240731.csv", encoding='euc-kr')
df_park.head(5)

,시군명,소공원_개소,소공원_면적,어린이공원_개소,어린이공원_면적,근린공원_개소,근린공원_면적,역사공원_개소,역사공원_면적,문화공원_개소,문화공원_면적,수변공원_개소,수변공원_면적,묘지공원_개소,묘지공원_면적,체육공원_개소,체육공원_면적
0,창원시,119.0,284387.0,239.0,606045.0,85,12447331,2,30637,13,374677,5,125745,3,3337183,10,785136
1,진주시,30.0,72795.0,66.0,145978.0,48,6594836,5,243628,7,181733,7,137607,,,1,17629
2,통영시,18.0,41809.0,15.0,50250.0,7,2902888,1,8593,2,159480,2,70591,,,1,250287
3,사천시,46.0,113468.0,28.0,82333.0,32,1354365,3,273563,7,152203,1,9782,,,1,13635
4,김해시,79.0,209918.0,168.0,355546.0,65,4310292,2,123947,2,62490,7,65931,,,4,372340

In [8]:
df_park=df_park[df_park['시군명'].isin(["창원시", "김해시", "산청군", "의령군"])]
df_park

,시군명,소공원_개소,소공원_면적,어린이공원_개소,어린이공원_면적,근린공원_개소,근린공원_면적,역사공원_개소,역사공원_면적,문화공원_개소,문화공원_면적,수변공원_개소,수변공원_면적,묘지공원_개소,묘지공원_면적,체육공원_개소,체육공원_면적
0,창원시,119.0,284387.0,239.0,606045.0,85,12447331,2,30637,13,374677,5,125745,3,3337183,10,785136
4,김해시,79.0,209918.0,168.0,355546.0,65,4310292,2,123947,2,62490,7,65931,,,4,372340
8,의령군,14.0,30086.0,5.0,13377.0,7,1228959,1,32108,3,204790,,,,,2,57917
14,산청군,8.0,16603.0,1.0,2978.0,5,298396,NaN,,4,63860,2,104904,,,2,42931

In [10]:
df_park.fillna(0, inplace=True)

공연장 데이터 처리

In [20]:
df_concert = pd.read_csv(r"D:\MINNIE\contest_gyeongnam_data_analysis\data\인허가공연장.csv", encoding='euc-kr')
df_concert.head(5)

,사업장명,지번주소,도로명주소,인허가일자,영업상태,상세영업상태
0,날개,경상남도 진주시 대안동 20-3,경상남도 진주시 진양호로527번길 4-1 (대안동),2018-03-15,영업/정상,영업중
1,문희정아트홀,경상남도 진주시 충무공동 29-6번지,경상남도 진주시 에나로77번길 12 (충무공동),2017-07-07,영업/정상,영업중
2,VK아트홀,경상남도 진주시 내동면 470-1,경상남도 진주시 내동면 내동로 213,2016-02-04,영업/정상,영업중
3,현장아트홀,경상남도 진주시 동성동 5-5,경상남도 진주시 진주대로 1038 (동성동),2007-09-20,영업/정상,영업중
4,진주시 전통예술회관 공연장,경상남도 진주시 판문동 산 171-1번지,경상남도 진주시 남강로1번길 96-6 (판문동),2003-03-08,영업/정상,영업중

In [21]:
df_concert['시군구'] = df_concert['지번주소'].str.extract(r'^(\S+\s\S+)')
df_concert.head(5)

,사업장명,지번주소,도로명주소,인허가일자,영업상태,상세영업상태,시군구
0,날개,경상남도 진주시 대안동 20-3,경상남도 진주시 진양호로527번길 4-1 (대안동),2018-03-15,영업/정상,영업중,경상남도 진주시
1,문희정아트홀,경상남도 진주시 충무공동 29-6번지,경상남도 진주시 에나로77번길 12 (충무공동),2017-07-07,영업/정상,영업중,경상남도 진주시
2,VK아트홀,경상남도 진주시 내동면 470-1,경상남도 진주시 내동면 내동로 213,2016-02-04,영업/정상,영업중,경상남도 진주시
3,현장아트홀,경상남도 진주시 동성동 5-5,경상남도 진주시 진주대로 1038 (동성동),2007-09-20,영업/정상,영업중,경상남도 진주시
4,진주시 전통예술회관 공연장,경상남도 진주시 판문동 산 171-1번지,경상남도 진주시 남강로1번길 96-6 (판문동),2003-03-08,영업/정상,영업중,경상남도 진주시

In [22]:
df_concert=df_concert[df_concert['시군구'].isin(["경상남도 창원시", "경상남도 김해시", "경상남도 산청군", "경상남도 의령군"])]
df_concert.head(10)

,사업장명,지번주소,도로명주소,인허가일자,영업상태,상세영업상태,시군구
17,김해시립공연장,경상남도 김해시 삼방동 192번지,경상남도 김해시 활천로285번길 14 (삼방동),2004-10-06,영업/정상,영업중,경상남도 김해시
18,장유도서관 공연장,경상남도 김해시 대청동 299번지 17통4반,경상남도 김해시 대청로176번길 7 (대청동),2004-10-06,영업/정상,영업중,경상남도 김해시
19,김해문화원,경상남도 김해시 외동 1261-4번지,경상남도 김해시 분성로 225 (외동),2004-10-06,영업/정상,영업중,경상남도 김해시
20,김해문화의전당 마루홀,경상남도 김해시 내동 1131번지,"경상남도 김해시 김해대로 2060 (내동, 김해문화의전당)",2006-02-01,영업/정상,영업중,경상남도 김해시
21,김해문화의전당 누리홀,경상남도 김해시 내동 1131번지,"경상남도 김해시 김해대로 2060 (내동, 김해문화의전당)",2007-06-26,영업/정상,영업중,경상남도 김해시
22,회현동 소극장,경상남도 김해시 봉황동 461-3번지,"경상남도 김해시 분성로 259, 4층 (봉황동)",2019-08-27,영업/정상,영업중,경상남도 김해시
23,김해문화의전당 애두름마당,경상남도 김해시 내동 1131번지,"경상남도 김해시 김해대로 2060, 1층 (내동, 김해문화의전당)",2007-06-26,영업/정상,영업중,경상남도 김해시
24,진영한빛도서관 누리마을,경상남도 김해시 진영읍 여래리 530-2번지,경상남도 김해시 진영읍 김해대로 440 (진영한빛도서관),2010-07-09,영업/정상,영업중,경상남도 김해시
25,철광산 공연장,경상남도 김해시 어방동 993번지,경상남도 김해시 가야테마길 161 (어방동),2015-05-21,영업/정상,영업중,경상남도 김해시
26,김해서부문화센터 하늬홀,경상남도 김해시 율하동 1377번지,경상남도 김해시 율하2로 210 (율하동),2018-08-03,영업/정상,영업중,경상남도 김해시

In [23]:
df_concert = df_concert[df_concert['상세영업상태'] == "영업중"]
df_concert['시군구'] = df_concert['시군구'].str[-3:]
df_concert.head(5)

,사업장명,지번주소,도로명주소,인허가일자,영업상태,상세영업상태,시군구
17,김해시립공연장,경상남도 김해시 삼방동 192번지,경상남도 김해시 활천로285번길 14 (삼방동),2004-10-06,영업/정상,영업중,김해시
18,장유도서관 공연장,경상남도 김해시 대청동 299번지 17통4반,경상남도 김해시 대청로176번길 7 (대청동),2004-10-06,영업/정상,영업중,김해시
19,김해문화원,경상남도 김해시 외동 1261-4번지,경상남도 김해시 분성로 225 (외동),2004-10-06,영업/정상,영업중,김해시
20,김해문화의전당 마루홀,경상남도 김해시 내동 1131번지,"경상남도 김해시 김해대로 2060 (내동, 김해문화의전당)",2006-02-01,영업/정상,영업중,김해시
21,김해문화의전당 누리홀,경상남도 김해시 내동 1131번지,"경상남도 김해시 김해대로 2060 (내동, 김해문화의전당)",2007-06-26,영업/정상,영업중,김해시

In [24]:
df_concert = df_concert[["시군구", "지번주소"]]
df_concert.head(5)

#지번주소 지오코딩 필요

    시군구                       지번주소
17  김해시        경상남도 김해시 삼방동 192번지
18  김해시  경상남도 김해시 대청동 299번지 17통4반
19  김해시      경상남도 김해시 외동 1261-4번지
20  김해시        경상남도 김해시 내동 1131번지
21  김해시        경상남도 김해시 내동 1131번지

In [38]:
df_concert['구분'] = "공연장"
df_concert.head(5)

    시군구                       지번주소   구분
17  김해시        경상남도 김해시 삼방동 192번지   공연장
18  김해시  경상남도 김해시 대청동 299번지 17통4반   공연장
19  김해시      경상남도 김해시 외동 1261-4번지   공연장
20  김해시        경상남도 김해시 내동 1131번지   공연장
21  김해시        경상남도 김해시 내동 1131번지   공연장

문화관광 시설

In [33]:
df_culture = pd.read_csv(r"D:\MINNIE\contest_gyeongnam_data_analysis\data\인허가문화관광시설.csv", encoding='euc-kr')
df_culture.head(5)

,사업장명,지번주소,도로명주소,인허가일자,영업상태,상세영업상태,구분
0,거제랜드,경상남도 거제시 고현동 362번지 거제포로수용소유적공원,"경상남도 거제시 계룡로 61, 거제포로수용소유적공원 (고현동)",2019-05-03,영업/정상,영업중,일반유원시설업
1,쌍계사,경상남도 하동군 화개면 운수리 208,경상남도 하동군 화개면 쌍계사길 59,1988-06-10,영업/정상,NaN,전통사찰
2,리틀비틀(죽림점),경상남도 통영시 광도면 죽림리 1575-7 알파문구,"경상남도 통영시 광도면 죽림2로 49-27, 알파문구 2층",2018-11-22,영업/정상,영업중,유원시설업(기타)
3,용원 트램플린 방방,경상남도 창원시 진해구 용원동 1211-1,"경상남도 창원시 진해구 안골로 348, 2층 202,203호 (용원동, 용원그랜드쇼핑)",2017-09-05,영업/정상,영업중,유원시설업(기타)
4,합천휴테마파크,경상남도 합천군 용주면 가호리 1180,경상남도 합천군 용주면 영상로 172,2020-12-14,영업/정상,영업중,유원시설업(기타)

In [34]:
df_culture['시군구'] = df_culture['지번주소'].str.extract(r'^(\S+\s\S+)')
df_culture.head(5)

,사업장명,지번주소,도로명주소,인허가일자,영업상태,상세영업상태,구분,시군구
0,거제랜드,경상남도 거제시 고현동 362번지 거제포로수용소유적공원,"경상남도 거제시 계룡로 61, 거제포로수용소유적공원 (고현동)",2019-05-03,영업/정상,영업중,일반유원시설업,경상남도 거제시
1,쌍계사,경상남도 하동군 화개면 운수리 208,경상남도 하동군 화개면 쌍계사길 59,1988-06-10,영업/정상,NaN,전통사찰,경상남도 하동군
2,리틀비틀(죽림점),경상남도 통영시 광도면 죽림리 1575-7 알파문구,"경상남도 통영시 광도면 죽림2로 49-27, 알파문구 2층",2018-11-22,영업/정상,영업중,유원시설업(기타),경상남도 통영시
3,용원 트램플린 방방,경상남도 창원시 진해구 용원동 1211-1,"경상남도 창원시 진해구 안골로 348, 2층 202,203호 (용원동, 용원그랜드쇼핑)",2017-09-05,영업/정상,영업중,유원시설업(기타),경상남도 창원시
4,합천휴테마파크,경상남도 합천군 용주면 가호리 1180,경상남도 합천군 용주면 영상로 172,2020-12-14,영업/정상,영업중,유원시설업(기타),경상남도 합천군

In [35]:
df_culture=df_culture[df_culture['시군구'].isin(["경상남도 창원시", "경상남도 김해시", "경상남도 산청군", "경상남도 의령군"])]
df_culture.head(10)

,사업장명,지번주소,도로명주소,인허가일자,영업상태,상세영업상태,구분,시군구
3,용원 트램플린 방방,경상남도 창원시 진해구 용원동 1211-1,"경상남도 창원시 진해구 안골로 348, 2층 202,203호 (용원동, 용원그랜드쇼핑)",2017-09-05,영업/정상,영업중,유원시설업(기타),경상남도 창원시
5,롯데워터파크,경상남도 김해시 신문동 1417,경상남도 김해시 장유로 555 (신문동),2014-05-01,영업/정상,영업중,종합유원시설업,경상남도 김해시
26,샤랄랄라 키즈카페,경상남도 김해시 삼계동 1502-2 삼성아동병원 3층,"경상남도 김해시 삼계중앙로 36, 삼성아동병원 3층 (삼계동)",2018-01-23,영업/정상,영업중,유원시설업(기타),경상남도 김해시
27,온가족 놀이터,경상남도 김해시 동상동 992-12번지,경상남도 김해시 분성로 337 (동상동),2016-11-07,영업/정상,영업중,유원시설업(기타),경상남도 김해시
28,야사노,경상남도 김해시 외동 1259-2번지 힐튼상가 401호,"경상남도 김해시 함박로119번길 23, 401호 (외동, 힐튼상가)",2016-09-08,영업/정상,영업중,유원시설업(기타),경상남도 김해시
29,마크원,경상남도 김해시 외동 1252-2번지 삼우빌딩 108호,"경상남도 김해시 함박로101번길 22, 108호 (외동, 삼우빌딩)",2016-08-17,영업/정상,영업중,유원시설업(기타),경상남도 김해시
30,헬로방방 김해율하,경상남도 김해시 율하동 1335-1번지 경보월드,"경상남도 김해시 율하2로97번길 22, 경보월드 7층 (율하동)",2018-02-12,영업/정상,영업중,유원시설업(기타),경상남도 김해시
31,스카이 봉봉장,경상남도 김해시 삼계동 1422-4,NaN,2018-07-02,영업/정상,영업중,유원시설업(기타),경상남도 김해시
32,닥터밸런스 김해점,경상남도 김해시 신문동 1414번지 롯데아울렛신관,"경상남도 김해시 장유로 469, 롯데아울렛신관 4층 (신문동)",2018-05-01,영업/정상,영업중,유원시설업(기타),경상남도 김해시
33,장유스파랜드,경상남도 김해시 삼문동 562-12번지,"경상남도 김해시 대청로104번길 84, 장유스파랜드 (삼문동)",2018-08-23,영업/정상,영업중,유원시설업(기타),경상남도 김해시

In [36]:
df_culture = df_culture[df_culture['상세영업상태'] == "영업중"]
df_culture['시군구'] = df_culture['시군구'].str[-3:]
df_culture.head(5)

,사업장명,지번주소,도로명주소,인허가일자,영업상태,상세영업상태,구분,시군구
3,용원 트램플린 방방,경상남도 창원시 진해구 용원동 1211-1,"경상남도 창원시 진해구 안골로 348, 2층 202,203호 (용원동, 용원그랜드쇼핑)",2017-09-05,영업/정상,영업중,유원시설업(기타),창원시
5,롯데워터파크,경상남도 김해시 신문동 1417,경상남도 김해시 장유로 555 (신문동),2014-05-01,영업/정상,영업중,종합유원시설업,김해시
26,샤랄랄라 키즈카페,경상남도 김해시 삼계동 1502-2 삼성아동병원 3층,"경상남도 김해시 삼계중앙로 36, 삼성아동병원 3층 (삼계동)",2018-01-23,영업/정상,영업중,유원시설업(기타),김해시
27,온가족 놀이터,경상남도 김해시 동상동 992-12번지,경상남도 김해시 분성로 337 (동상동),2016-11-07,영업/정상,영업중,유원시설업(기타),김해시
28,야사노,경상남도 김해시 외동 1259-2번지 힐튼상가 401호,"경상남도 김해시 함박로119번길 23, 401호 (외동, 힐튼상가)",2016-09-08,영업/정상,영업중,유원시설업(기타),김해시

In [37]:
df_culture = df_culture[["시군구", "지번주소", "구분"]]
df_culture.head(5)

#지번주소 지오코딩 필요

    시군구                            지번주소         구분
3   창원시        경상남도 창원시 진해구 용원동 1211-1   유원시설업(기타)
5   김해시              경상남도 김해시 신문동 1417     종합유원시설업
26  김해시  경상남도 김해시 삼계동 1502-2 삼성아동병원 3층   유원시설업(기타)
27  김해시          경상남도 김해시 동상동 992-12번지   유원시설업(기타)
28  김해시  경상남도 김해시 외동 1259-2번지 힐튼상가 401호  유원시설업(기타)

박물관

In [39]:
df_museum = pd.read_csv(r"D:\MINNIE\contest_gyeongnam_data_analysis\data\박물관.csv", encoding='euc-kr')
df_museum.head(5)

,팩스번호,연락처,홈페이지,소재지,관리기관명,기관명,시군구명,고유번호
0,-,055-673-4951,http://www.okcheonsa.or.kr/,경상남도 고성군 개천면 연화산1로 471-9,NaN,옥천사성보박물관,고성군,4078015
1,055-345-7785,055-345-7736,-,김해시 한림면 김해대로 1029-20,NaN,한림민속박물관,김해시,2066849
2,055-632-0672,055-632-0670,www.hggmuseum.com/,거제시 남부면 해금강로 120,NaN,해금강테마박물관,거제시,2066848
3,-,055-670-2825,museum.goseong.go.kr,고성군 하이면 자란만로 618,NaN,고성공룡박물관,고성군,2066846
4,055-580,055-580-3901,museum.haman.go.kr,함안군 가야읍 고분길 153-31,NaN,함안박물관,함안군,2066844

In [42]:
df_museum = df_museum[df_museum['시군구명'].isin(['산청군', '창원시', '김해시', '의령군'])]
df_museum.head(5)

,팩스번호,연락처,홈페이지,소재지,관리기관명,기관명,시군구명,고유번호
1,055-345-7785,055-345-7736,-,김해시 한림면 김해대로 1029-20,NaN,한림민속박물관,김해시,2066849
5,-,055-331-2357,ds.gimhae.go.kr,김해시 가야의길 126 (대성동),NaN,대성동고분박물관,김해시,2066843
7,-,055-549-1180,museum.navy.ac.kr,창원시 진해구 중원로 1,NaN,해군사관학교 박물관,창원시,2066839
17,-,055-548-2053,-,창원시 진해구 중원동로 52 (제황산동),NaN,창원시립진해박물관,창원시,2066214
20,-,055-320-3178,injemuseum.inje.ac.kr,김해시 인제로 197 (어방동),NaN,인제대학교박물관,김해시,2066208

In [47]:
df_museum = df_museum[["시군구명", "소재지"]]
df_museum['구분'] ="박물관"
df_museum.head(4)

   시군구명                     소재지   구분
1   김해시    김해시 한림면 김해대로 1029-20  박물관
5   김해시      김해시 가야의길 126 (대성동)  박물관
7   창원시           창원시 진해구 중원로 1  박물관
17  창원시  창원시 진해구 중원동로 52 (제황산동)  박물관

미술관

In [45]:
df_art = pd.read_csv(r"D:\MINNIE\contest_gyeongnam_data_analysis\data\미술관.csv", encoding='euc-kr')
df_art

,팩스번호,연락처,홈페이지,소재지,관리기관명,기관명,시군구명,고유번호
0,055-211-5319,055-749-3663,http://www.jinju.go.kr/rheesjmuseum/,경상남도 진주시 에나로 128번길 14,NaN,진주시립이성자미술관,진주시,2067572
1,-,055-747-7220,-,진주시 명석면 광제산로257번길 46,NaN,진주미술관,진주시,2066221
2,-,055-645-7349,-,통영시 봉평동 189-2,NaN,전혁림미술관,통영시,2066220
3,055-340-7077,055-340-7000,www.clayarch.org,김해시 진례면 진례로 275-51,NaN,클레이아크 김해미술관,김해시,2066219
4,-,055-291-5237,http://www.daesanart.com,창원시 의창구 대산면 유등로,NaN,대산미술관,창원시,2066218
5,055-649-5357,055-649-5257,https://tyottchil.modoo.at/,통영시 용남면 용남해안로 36,NaN,통영옻칠미술관,통영시,2066217
6,-,055-220-6550,https://www.changwon.go.kr/depart/contents.do?...,창원시 마산합포구 문신1길 71 (추산동),NaN,문신미술관,창원시,2066216
7,-,055-254-4600,https://www.gyeongnam.go.kr/gam/index.gyeong,창원시 의창구 용지로 296(경남도립미술관),NaN,경남도립미술관,창원시,2066215

In [46]:
df_art = df_art[df_art['시군구명'].isin(['산청군', '창원시', '김해시', '의령군'])]
df_art.head(5)

,팩스번호,연락처,홈페이지,소재지,관리기관명,기관명,시군구명,고유번호
3,055-340-7077,055-340-7000,www.clayarch.org,김해시 진례면 진례로 275-51,NaN,클레이아크 김해미술관,김해시,2066219
4,-,055-291-5237,http://www.daesanart.com,창원시 의창구 대산면 유등로,NaN,대산미술관,창원시,2066218
6,-,055-220-6550,https://www.changwon.go.kr/depart/contents.do?...,창원시 마산합포구 문신1길 71 (추산동),NaN,문신미술관,창원시,2066216
7,-,055-254-4600,https://www.gyeongnam.go.kr/gam/index.gyeong,창원시 의창구 용지로 296(경남도립미술관),NaN,경남도립미술관,창원시,2066215

In [48]:
df_art = df_art[["시군구명", "소재지"]]
df_art['구분'] = '미술관'
df_art.head(5)

  시군구명                       소재지   구분
3  김해시        김해시 진례면 진례로 275-51  미술관
4  창원시           창원시 의창구 대산면 유등로  미술관
6  창원시   창원시 마산합포구 문신1길 71 (추산동)  미술관
7  창원시  창원시 의창구 용지로 296(경남도립미술관)  미술관

문화행사

In [11]:
df_festival = pd.read_csv(r"D:\MINNIE\contest_gyeongnam_data_analysis\data\문화행사.csv", encoding='euc-kr')
df_festival.head(5)

,시군명,연락처,행사주최,장소,시간,행사종료일,행사시작일,내용,제목,고유번호
0,합천군,055-930-3172,합천색소폰동호회,합천군 문화예술회관 공연장,17:00,2022-12-03,2022-12-03,합천색소폰 정기연주회,합천색소폰 정기연주회,41843048
1,합천군,055-930-3184,합천군합창단,합천군 문화예술회관 공연장,19:00,2022-12-01,2022-12-01,합천군합창단 정기연주회,제21회 합천군합창단 정기연주회,41843047
2,거창군,055-940-8460,(재)거창문화재단,거창문화센터공연장,19:30,2022-12-07,2022-12-07,공연내용 : 거창문화재단 문화아카데미 성과발표회 입장료 : 무료,2022 거창문화재단 문화아카데미 성과발표회,41843046
3,거창군,055-940-8460,한국사진작가협회거창지부,거창문화센터전시실,10:00 ~ 18:00,2022-12-10,2022-12-06,전시내용 : 한국사진작가 협회 거창지부 사진 전시입장료 : 무료,대관전시한국사진작가 협회 거창지부 정기회원전,41843045
4,거창군,055-940-8460,(재)거창문화재단,거창문화센터전시실,10:00 ~ 18:00,2022-12-03,2022-11-29,전시내용 :순수예술활성화육성지원사업 선정 작가 사진전시입장료 : 무료,최일수 사진전흑백으로 黃山을 담다,41843044

In [12]:
df_festival = df_festival[df_festival['시군명'].isin(['산청군', '창원시', '김해시', '의령군'])]
df_festival.head(5)

,시군명,연락처,행사주최,장소,시간,행사종료일,행사시작일,내용,제목,고유번호
17,산청군,055-970-6404,산청군·산청군기독교연합회,산청실내체육관,14:30,2022-12-11,2022-12-11,"산청군민과 함께하는 성탄음악회(지역가수 천가연, 청소년 중창단 등)",성탄음악회,41843030
18,산청군,055-970-6405,산청군·산청매구보존회,산청문화예술회관 대공연장,14:30,2022-12-22,2022-12-22,제15회 산청매구보존회 정기공연,산청매구보존회 전통민속공연,41843029
102,김해시,031-633-4864,극단 가람,김해문화의전당누리홀,11:0013:0015:00,2022-12-31,2022-12-31,그림책 작가 앤서니 브라운의 작품의 엄마의 소중함과 행복한가정의 필요조건을 배우는 가족극,앤서니브라운의 돼지책,41842944
103,김해시,055-320-1234,(재)김해문화재단,김해문화의전당누리홀,11:0014:00,2022-12-29,2022-12-29,"발달장애를 가진 아동과 청소년, 성인 관객의 도전적 행동이나 특별한 소리, 감각적 ...",미디어퍼포먼스<노래가되자>,41842943
104,김해시,055-320-1234,(재)김해문화재단,김해문화의전당마루홀,19:30,2022-12-30,2022-12-29,작곡가 푸치니의 오페라 중 가장 비극적이고 사실적인 ‘토스카’는 경건하고 성스러운 ...,오페라 토스카,41842942

In [13]:
df_festival.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2051 entries, 17 to 4989
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시군명     2051 non-null   object
 1   연락처     2020 non-null   object
 2   행사주최    2051 non-null   object
 3   장소      2051 non-null   object
 4   시간      2051 non-null   object
 5   행사종료일   2051 non-null   object
 6   행사시작일   2051 non-null   object
 7   내용      2051 non-null   object
 8   제목      2051 non-null   object
 9   고유번호    2051 non-null   int64
dtypes: int64(1), object(9)
memory usage: 176.3+ KB

In [14]:
df_festival['행사시작일'] = pd.to_datetime(df_festival['행사시작일'], errors='coerce')
df_festival['행사종료일'] = pd.to_datetime(df_festival['행사종료일'], errors='coerce')

df_festival.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2051 entries, 17 to 4989
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시군명     2051 non-null   object
 1   연락처     2020 non-null   object
 2   행사주최    2051 non-null   object
 3   장소      2051 non-null   object
 4   시간      2051 non-null   object
 5   행사종료일   2051 non-null   datetime64[ns]
 6   행사시작일   2047 non-null   datetime64[ns]
 7   내용      2051 non-null   object
 8   제목      2051 non-null   object
 9   고유번호    2051 non-null   int64
dtypes: datetime64[ns](2), int64(1), object(7)
memory usage: 176.3+ KB

In [15]:
df_festival['행사일수'] = (df_festival['행사종료일'] - df_festival['행사시작일']).dt.days + 1
df_festival.head()

,시군명,연락처,행사주최,장소,시간,행사종료일,행사시작일,내용,제목,고유번호,행사일수
17,산청군,055-970-6404,산청군·산청군기독교연합회,산청실내체육관,14:30,2022-12-11,2022-12-11,"산청군민과 함께하는 성탄음악회(지역가수 천가연, 청소년 중창단 등)",성탄음악회,41843030,1.0
18,산청군,055-970-6405,산청군·산청매구보존회,산청문화예술회관 대공연장,14:30,2022-12-22,2022-12-22,제15회 산청매구보존회 정기공연,산청매구보존회 전통민속공연,41843029,1.0
102,김해시,031-633-4864,극단 가람,김해문화의전당누리홀,11:0013:0015:00,2022-12-31,2022-12-31,그림책 작가 앤서니 브라운의 작품의 엄마의 소중함과 행복한가정의 필요조건을 배우는 가족극,앤서니브라운의 돼지책,41842944,1.0
103,김해시,055-320-1234,(재)김해문화재단,김해문화의전당누리홀,11:0014:00,2022-12-29,2022-12-29,"발달장애를 가진 아동과 청소년, 성인 관객의 도전적 행동이나 특별한 소리, 감각적 ...",미디어퍼포먼스<노래가되자>,41842943,1.0
104,김해시,055-320-1234,(재)김해문화재단,김해문화의전당마루홀,19:30,2022-12-30,2022-12-29,작곡가 푸치니의 오페라 중 가장 비극적이고 사실적인 ‘토스카’는 경건하고 성스러운 ...,오페라 토스카,41842942,2.0

In [16]:
df_festival = df_festival.groupby("시군명")["행사일수"].sum().reset_index()
df_festival = df_festival.rename(columns={"행사일수": "총행사일수"})

In [17]:
df_festival.head(5)

   시군명    총행사일수
0  김해시  12514.0
1  산청군    259.0
2  의령군    218.0
3  창원시  11255.0

문화예술회관

In [ ]:
df_art = pd.read_csv(r"D:\MINNIE\contest_gyeongnam_data_analysis\data\미술관.csv", encoding='euc-kr')
df_art